set(_CATKIN_CURRENT_PACKAGE "faulhaber")
set(faulhaber_VERSION "0.0.0")
set(faulhaber_MAINTAINER "cirlab <cirlab@todo.todo>")
set(faulhaber_PACKAGE_FORMAT "2")
set(faulhaber_BUILD_DEPENDS "roscpp" "std_msgs" "my_ros_library")
set(faulhaber_BUILD_EXPORT_DEPENDS "roscpp" "std_msgs" "my_ros_library")
set(faulhaber_BUILDTOOL_DEPENDS "catkin")
set(faulhaber_BUILDTOOL_EXPORT_DEPENDS )
set(faulhaber_EXEC_DEPENDS "roscpp" "std_msgs" "my_ros_library")
set(faulhaber_RUN_DEPENDS "roscpp" "std_msgs" "my_ros_library")
set(faulhaber_TEST_DEPENDS )
set(faulhaber_DOC_DEPENDS )
set(faulhaber_URL_WEBSITE "")
set(faulhaber_URL_BUGTRACKER "")
set(faulhaber_URL_REPOSITORY "")
set(faulhaber_DEPRECATED "")