set(_CATKIN_CURRENT_PACKAGE "my_ros_library")
set(my_ros_library_VERSION "0.0.0")
set(my_ros_library_MAINTAINER "cirlab <cirlab@todo.todo>")
set(my_ros_library_PACKAGE_FORMAT "2")
set(my_ros_library_BUILD_DEPENDS "actionlib" "actionlib_msgs" "message_generation" "my_ros_action" "roscpp" "rospy" "std_msgs" "image_transport" "tf")
set(my_ros_library_BUILD_EXPORT_DEPENDS "actionlib" "actionlib_msgs" "my_ros_action" "roscpp" "rospy" "std_msgs" "image_transport" "tf")
set(my_ros_library_BUILDTOOL_DEPENDS "catkin")
set(my_ros_library_BUILDTOOL_EXPORT_DEPENDS )
set(my_ros_library_EXEC_DEPENDS "actionlib" "actionlib_msgs" "message_generation" "my_ros_action" "roscpp" "rospy" "std_msgs" "image_transport" "tf" "message_runtime")
set(my_ros_library_RUN_DEPENDS "actionlib" "actionlib_msgs" "message_generation" "my_ros_action" "roscpp" "rospy" "std_msgs" "image_transport" "tf" "message_runtime")
set(my_ros_library_TEST_DEPENDS )
set(my_ros_library_DOC_DEPENDS )
set(my_ros_library_URL_WEBSITE "")
set(my_ros_library_URL_BUGTRACKER "")
set(my_ros_library_URL_REPOSITORY "")
set(my_ros_library_DEPRECATED "")